#!/bin/bash


function help()
{
echo 'HELP
Usage:
hdmi -m, --mirror: mirror diplay
hdmi -j, --join: join display
hdmi -a, --analog: changes sound output to analog-stereo
hdmi -hd, --hdmi: changes sound output to hdmi-stereo
hdmi -h, --help: calls this help function
'
}


#list cards using pacmd and get index.
#cardindex= "pacmd list-cards | grep index:"

#some beforehand verifications
if [ $# -gt 1 ];
then
echo "Invalid number of parameters"
exit

fi


#execute
display1=$(xrandr --query | grep -w connected | head -n1 | cut -d " " -f1)
display2=$(xrandr --query | grep -w connected | sed -n 2p | cut -d " " -f1)


case $1 in

"-m")

echo "Mirrorring displays $display1 and $display2"
xrandr --output $display1 --auto --primary --output $display2 --auto --same-as $display1 ;;

"--mirror")

echo -n "Mirrorring displays $display1 and $display2"
xrandr --output $display1 --auto --primary --output $display2 --auto --same-as $display1 ;;

"-j")

echo "Joining displays $display1 and $display2"
xrandr --output $display1 --auto --primary --output $display2 --auto --right-of $display1 ;;

"--join")

echo "Joining displays $display1 and $display2"
xrandr --output $display1 --auto --primary --output $display2 --auto --right-of $display1 ;;

"-a")

echo "changing sound output to analog-stereo"
pacmd set-card-profile 0 output:analog-stereo ;;

"--analog") 

echo "changing sound output to analog-stereo"
pacmd set-card-profile 0 output:analog-stereo ;;

"-hd") 

echo "changing sound output to hdmi-stereo"
pacmd set-card-profile 0 output:hdmi-stereo ;;

"--hdmi")

echo "changing sound output to hdmi-stereo"
pacmd set-card-profile 0 output:hdmi-stereo ;;

"-h")
help ;;

"--help")
help ;;

*)

echo "Invalid option"
help ;;

esac
